spring.application.name=MinInventario4BM2
server.port=8085

# Configuración para PostgreSQL en Docker
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.url=jdbc:postgresql://localhost:5433/nombreDeLaBaseDeDatos
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=admin
spring.datasource.password=WvXdvtrvvcE533WnUNgVxTHrMF5ehH
spring.datasource.url=jdbc:postgresql://mx-central-1.18c3702d-f838-405c-b40c-7adcc9e89758.aws.yugabyte.cloud:5433/yugabyte
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forzar el dialecto (esto evita el error de "Unable to determine Dialect")
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estrategias de nombrado (opcional, pero ayuda a que coincidan con SQL)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

#Documentacion
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/documentacion/swagger-ui.html
springdoc.paths-to-match=/api/v1/categorias/**, /api/v1/productos/**


#http://localhost:8085/documentacion/swagger-ui.html

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.mail.username=dmalvaezsescom@gmail.com


spring.mail.password=ernvducgkpqggtne
